//THIS CODE IS AUTOGENERATED, DO NOT OVERRIDE
public class SceneReference
{
    public string SceneName;
    public SceneReference(string sceneName)
    {
        SceneName = sceneName;
    }
    //AUTOGENERATED
    public static SceneReference SCENE_LoadingScene = new SceneReference("LoadingScene");
    public static SceneReference SCENE_SampleScene = new SceneReference("SampleScene");
}

